version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - unoserver
      - redis
    env_file: 
      - path: ".env"
        required: true

  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19-9c28c22
    ports:
      - "2002:2002"

  redis:
    image: redis:6.2
    ports:
      - "6342:6342"
