services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app
    env_file: 
      - path: ".env"
        required: true
    restart: always

  redis:
    image: redis:6.2
    ports:
      - "6342:6379"
